# -*- coding: utf-8 -*-
{
    'name': 'LHI Asset Register',
    'version': '19.0.2.0.1',
    'category': 'Operations',
    'summary': 'Operational Asset Register, tags, imports and lifecycle history',
    'author': 'Life Helpers Initiative',
    'website': 'https://work.lhinigeria.org',
    'depends': [
        'mail',
        'stock',
        'lhi_base',
        'lhi_security',
        'lhi_audit',
        'lhi_purchase_order',
        'lhi_approval_matrix',
        'lhi_sharepoint_storage',
        'lhi_web_shell',
    ],
    'external_dependencies': {'python': ['openpyxl']},
    'data': [
        'security/ir.model.access.csv',
        'security/lhi_asset_security.xml',
        'data/ir_sequence_data.xml',
        'data/lhi_asset_configuration_data.xml',
        'views/lhi_asset_views.xml',
        'views/lhi_asset_transfer_views.xml',
        'views/lhi_asset_retag_views.xml',
        'views/lhi_asset_import_views.xml',
        'views/lhi_asset_configuration_views.xml',
        'report/lhi_asset_reports.xml',
        'report/lhi_asset_report_templates.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'lhi_asset_management/static/src/js/asset_dashboard.js',
            'lhi_asset_management/static/src/xml/asset_dashboard.xml',
            'lhi_asset_management/static/src/scss/asset_dashboard.scss',
        ],
        'web.assets_unit_tests': [
            'lhi_asset_management/static/tests/asset_dashboard.test.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
