[options]
admin_passwd = admin_master_secret
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_db_password
db_name = lhi_erp_dev
addons_path = /opt/odoo/odoo/addons,/opt/odoo/custom-addons
logfile = /var/log/odoo/odoo.log
log_level = info
log_handler = :INFO,odoo.addons.lhi_audit:DEBUG
workers = 0
max_cron_threads = 2
limit_memory_soft = 1610612736
limit_memory_hard = 2147483648
limit_time_cpu = 600
limit_time_real = 1200
