{
    "name": "LHI HUB Management",
    "version": "19.0.1.0.0",
    "category": "Operations",
    "summary": "HUB stock, requests, consignments, issues, leases and operational revenue",
    "author": "Life Helpers Initiative",
    "website": "https://work.lhinigeria.org",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "stock",
        "product_expiry",
        "lhi_fleet_operations",
        "lhi_inventory",
        "lhi_asset_management",
        "lhi_approval_matrix",
        "lhi_signature_bridge",
        "lhi_sharepoint_storage",
        "lhi_audit",
        "lhi_web_shell",
    ],
    "data": [
        "security/lhi_hub_security.xml",
        "security/ir.model.access.csv",
        "data/lhi_hub_sequence_data.xml",
        "data/lhi_hub_configuration_data.xml",
        "data/lhi_hub_storage_policy_data.xml",
        "data/lhi_hub_cron_data.xml",
        "views/lhi_hub_views.xml",
        "views/lhi_hub_product_views.xml",
        "views/lhi_hub_consignment_views.xml",
        "views/lhi_hub_request_views.xml",
        "views/lhi_hub_external_issue_views.xml",
        "views/lhi_hub_lease_views.xml",
        "views/lhi_hub_adjustment_views.xml",
        "views/lhi_hub_configuration_views.xml",
        "report/lhi_hub_reports.xml",
        "report/lhi_hub_report_templates.xml",
        "views/lhi_hub_menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lhi_hub_management/static/src/js/hub_dashboard.js",
            "lhi_hub_management/static/src/xml/hub_dashboard.xml",
            "lhi_hub_management/static/src/scss/hub_dashboard.scss",
        ],
        "web.assets_unit_tests": [
            "lhi_hub_management/static/tests/hub_dashboard.test.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
